image: docker:git

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  RELEASE_TAG: $CI_REGISTRY_IMAGE:latest

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - clinic_admin/node_modules
    - clinic_docs/node_modules

stages:
  - build
  - release

before_script:
#  - git submodule sync --recursive
#  - git submodule update --init --recursive
  - docker info
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - apk add yarn
  - cd clinic_admin && yarn && yarn run build && cd ..
  - cd clinic_docs && yarn && yarn docs:build && cd ..

build-image:
  stage: build
  script:
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  only:
    - master

build-release:
  stage: release
  script:
    - docker build -t $RELEASE_TAG .
    - docker push $RELEASE_TAG
  only:
    - deploy
