version: "2"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: clinic
    network_mode: bridge
  web:
    image: docker.bitnp.net/bitnp/clinic/clinic_django:master
    restart: always
    environment:
      apikey: ${APIKEY} # you must change that before deploy
      VIRTUAL_HOST: clinic.bitnp.net
      VIRTUAL_PORT: 80
      TZ: Asia/Shanghai
    network_mode: bridge
    links:
      - "db:db"
  mq:
    image: rabbitmq
    restart: always
