version: "2"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: clinic
  web:
    image: docker.bitnp.net/bitnp/clinic/clinic_django:local-build
    restart: always
    environment:
      VIRTUAL_HOST: clinic.bitnp.net
      VIRTUAL_PORT: 80
    network_mode: bridge